### ISSUE TITLE
Publish app on f-droid

### ISSUE THREAD

**Issue by xmr-karnal** [NickvanDyke/Sia-Android#10]
For those of us who prefer not to run google services on our devices, would it be possible to [include this app on f-droid](https://f-droid.org/en/docs/Inclusion_How-To) ?

I might also add that as far as I can see, the sort of user who goes through the trouble of learning how to install a custom rom without google services/apps on their device, is at this point probably also interested in cryptocurrency - publishing the app on [f-droid](https://f-droid.org) to hordes of foss fans seems like a good way to get some exposition with the right crowd!

**Comment by IzzySoft** [comment]
I second that request. Though it would require a special flavor that comes without Firebase, or it wouldn't be accepted at F-Droid.

Besides: is the APK currently available anywhere? The playstore link comes up with a 404.

**Comment by bookchin** [comment]
The app will be rejected from F-Droid because it is non-free, see the LICENSE. Perhaps this issue should instead be a appeal to the author to release this package under a free license.

**Comment by nickjvandyke** [comment]
Indeed, this app is not currently eligible for F-Droid because it:
- is not under an open source license
- uses Firebase for usage analytics
- uses Google Play Billing

If this app ever meets F-Droid's requirements, then I will happily publish it there. However I don't have plans for changing any of the above anytime soon. Sorry.
